### ISSUE TITLE
Operator arithmetic on stack variables

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/NasmX86#10]
@majorendian   A most important test. 

Might it be possible to automatically include the qword designator automatically in the output of sub LocalVariable::stack so that the users does not have to manually type it in each time?

**Comment by philiprbrenan** [comment]
@majorendian Another line of development to consider might be using operator overloading as we do for Vq variables on stack variables as well?

**Comment by majorendian** [comment]
You have made that change already, so I believe we can close this issue.

**Comment by philiprbrenan** [comment]
I have re-titled this issue: lets see if it is possible to provide code generation via operator overloading for stack variables to match global Variables?

**Comment by majorendian** [comment]
I have made test 21 for this since it is a slighlty different issue. Please see commit ef85a0fcc9d724a93814c701ff0ad96c74fff390
If you do not want to deal with the pull-request let me know and I'll include it directly into the main branch.
Some strange things were happening when I was testing this.

**Comment by philiprbrenan** [comment]
Arithmetic on stack variables via operator overloading as is done with global variables.
