### ISSUE TITLE
Demonstrate how to access the value returned by a C function 

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/NasmX86#28]
It would be useful to know how to access the values returned by functions, for instance: **malloc** ?

**Comment by majorendian** [comment]
Results are always in RAX as far as I am aware.
So
`CallC 'malloc', 64`
Would return a pointer to the newly allocated block in RAX

**Comment by philiprbrenan** [comment]
```
  CallC 'malloc', 16;
  PrintErrRegisterInHex rax;

   rax: 0000 0000 0000 001C
```

**Comment by majorendian** [comment]
You destroyed the value in RAX with your rewite. Please see the file I sent via email. Apply my fix, and run test 25_malloc.t

**Comment by philiprbrenan** [comment]
Excellent, please see: 

```
  my $format = Rs "Hello %s\n";
  my $data   = Rs "World";

  Extern qw(printf exit malloc strcpy); Link 'c';

  CallC 'malloc', length($format)+1;
  Mov r15, rax;
  CallC 'strcpy', r15, $format;
  CallC 'printf', r15, $data;
  CallC 'exit', 0;

  ok Assemble(eq => <<END);
Hello World
END
```

**Comment by majorendian** [comment]
Great! It works wonderfully.
I have made test 26_strcpy.t for this.
Also once again, please Export the new functions.

**Comment by philiprbrenan** [comment]
Please email me the functions you would like to see exported?

**Comment by majorendian** [comment]
CallC, Extern and Link

**Comment by philiprbrenan** [comment]
Now I understand!  10 minutes and I will have them in place....

**Comment by majorendian** [comment]
Thanks a lot!
