### ISSUE TITLE
Test 6

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/NasmX86#3]
@majorendian Test 6 looks good. You might find using **Variable::dump** a shorter and more meaningful way to output variables for testing purposes?

**Comment by majorendian** [comment]
I have written a slightly less conventional test for this in 6a.t with evals because the bitwise operations do not work as expected. I have used the dump methods there, since I also wanted to check the ->address methods of those variables since I find them to be very useful methods.

**Comment by majorendian** [comment]
see commit 09817b199fbaa473e5e5899e71c4cdccdcbc0c79

**Comment by philiprbrenan** [comment]
The reason for this is that && and || or (I believe) cannot be overridden in perl (which is annoying).  So I had to use & for and and | for or in the implementation of variables as and and or are very useful.  I think this explains why  you are not getting the results that you might otherwise expect.
