### ISSUE TITLE
Allocate memory in 08.t

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/NasmX86#6]
@majorendian Please add a comments like this:

if (1) {                                                   #TAllocateMemory  #TFreeMemory
code of test that tests AllocateMemory ....
}

So that the automated documentation system can pick up the relevant test code use it as an example of this subroutine in use?

**Comment by majorendian** [comment]
Ok I will do so. I appologize, I have not used the automated documentation system yet.

**Comment by majorendian** [comment]
I have done as you requested. I have also done this on all other tests. Please check if it is correct.

**Comment by philiprbrenan** [comment]
Please do not feel any need to apologize - it is marvelous to have your thoughts and ideas. The automated documentation system is quite useful as  it saves time maintaining documentation so even though it does restrict your actions somewhat the trade does seem favorable in that for a small amount of extra effort we save a lot of (boring) time spent writing documentation.

To get the most out of the the doc system please format something like this:


```
if (1) {                                                      #TKeepFree reg test
``` 

with spaces between elements and comments starting in column 80 if possible - if not I will take care of such minor formatting issues when I incorporate your latest tests.

**Comment by majorendian** [comment]
I have made the changes but you undid them somehow. see commit 8b129e630840b95820f7983cbbd7fbe6bb592ced
Please look into this or suggest a solution. Should I just keep submitting pull requests from all other branches?
And I will make sure to format it properly but my changes are getting lost.

**Comment by philiprbrenan** [comment]
Perhaps we should use perl pod comments in tests as this would free us from the restrictions opposed by the existing document extraction process?   Something like below?  The reason for doing this is that tests often become examples in the documentation - but the format imposed by updateDocumentation is quite restrictive which makes documenting larger tests difficult.  I.e. it is good for quickly documenting subroutines but not so useful for documenting complete tests.  Do you have any thoughts as to whether using pod in test this would be an improvement or not?  We would have to produced an automated procedure to include such documentation from the tests in  the documentation generated from the code  so that all the documentation can be generated in a github action and then reloaded into the repository to make it visible to potential users.  As you can see we are still working out the best procedures to use so it is likely to be chaotic for some time yet. 

=pod

Test Documentation

=cut

**Comment by philiprbrenan** [comment]
Or perhaps just those tests that we want to make into examples should have
more extensive documentation in pod format to help the user understand them
- whereas perhaps those tests that will not become examples need almost
none - just a comment at the top - as we should not waste our valuable time
doing work that the user will never benefit from?  I.e. time is valuable we
have to discover how to use it to best effect?

**Comment by majorendian** [comment]
I do believe that writting a typical =pod documentation is in line with standard perl module documentation. It is not a waste of time. When someone does a perldoc t/10.t for example they will find documentation. We could include this documentation in the module itself. Good documentation makes good modules. A user needs to have a clear idea of what they are doing in order to benefit from the module in the best capacity. Writing documentation in tests itself seems a bit of extra unnecessary work. That is why I pre-emptively created the examples/ directory for this specific purpose. We can write some small programs explaning how the module works alongside working examples people can check by themselves.

**Comment by philiprbrenan** [comment]
Jolly good!  May I urge that there should be a Perl script that assembles a
complete document from all the fragments of documentation?

**Comment by majorendian** [comment]
Yes that is a good idea. Parsing it will not be hard. I will do it and generate a .pod file which you can then incorrporate into your main documentation

**Comment by majorendian** [comment]
Created issue #25 for this
