### ISSUE TITLE
Division in 10.t

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/NasmX86#8]
@majorendian  You might also like to try:

sub Variable::divide($$)                                                        # Divide the left hand variable by the right hand variable and return 
sub Variable::mod($$)                                                           # Divide the left hand variable by the right hand variable and return the remainder as a new variable

**Comment by majorendian** [comment]
I have made the change you requested: bfc9af995c5087adb049f7dd0f804132e8c825b4
Let me know if I should expand the test or if this issue can be closed.

**Comment by philiprbrenan** [comment]
An excellent test - I can now see that I have failed to restore the registers correctly in Variable::division - fixed.
