### ISSUE TITLE
11.t

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/NasmX86#9]
@majorendian  Excellent test: You might like to write a dump routine for structure elements so that they can be written out directly rather than forcing you to unload them into a register and then print the register?  Some comments in the test might help explain it to a new user?

**Comment by philiprbrenan** [comment]
Perhaps we could take this further and make the entire **LocalData** interface look like the **Variable** interface.

**Comment by majorendian** [comment]
It would make sense since most of the time variables are declared inside functions and on the stack. But we need to be able to declare global variables as well so we do need 2 interfaces.

**Comment by philiprbrenan** [comment]
Variables are more efficient as no set up is required on subroutine entry and exit - which in the case of small subroutines can be more than the work actually done by the subroutine.

**Comment by majorendian** [comment]
Normaly arguments on 64bit linux systems are passed into rdi,rsi,rcx,rdx,r8,r9 the rest is on the stack I believe.

**Comment by philiprbrenan** [comment]
The calls to the Linux interface do indeed use the registers named in SaveFirstFour etc.

Please free to implement capabilities that facilitate using the stack as a means of passing parameters.

We follow the dictum from Perl - "There is always more than one way to do it".

**Comment by majorendian** [comment]
Alright, I'll see what I can do
